---
- hosts: all
  sudo: yes
  roles:
          - { role: magnus919.epel, when: ansible_distribution == 'CentOS' }
          - common

- hosts: etcd
  sudo: yes
  roles:
          - etcd

- hosts: masters
  sudo: yes
  roles:
          - kubernetes
          - master

- hosts: minions
  sudo: yes
  roles:
          - kubernetes
          - minion
