---
- hosts: all
  sudo: yes
  pre_tasks:
    - name: Install libselinux-python if CentOS 7
      yum: >
        name=libselinux-python
        state=present
      when: ansible_distribution == 'CentOS'
      tags: epel
  roles:
          - { role: magnus919.epel, when: ansible_distribution == 'CentOS', tags: epel }
          - common

- hosts: etcd
  sudo: yes
  roles:
          - etcd

- hosts: masters
  sudo: yes
  roles:
          - kubernetes
          - master

- hosts: minions
  sudo: yes
  roles:
          - kubernetes
          - minion
          - docker
