---
- name: Determine if Atomic
  command: "grep Atomic /etc/redhat-release"
  register: is_atomic
  always_run: true
  ignore_errors: yes
  changed_when: false

- name: Determine if RHEL7
  shell: "grep 'Red Hat Enterprise Linux.*release 7' /etc/redhat-release"
  register: is_rhel7
  always_run: true
  ignore_errors: yes
  changed_when: false

- name: Determine if CentOS 7
  shell: "grep 'CentOS Linux.*release 7' /etc/redhat-release"
  register: is_centos7
  always_run: true
  ignore_errors: yes
  changed_when: false

- include: rhel7_repos.yml
  when: is_rhel7.rc == 0 and is_atomic.rc != 0

- include: centos7_repos.yml
  when: is_centos7.rc == 0 and is_atomic.rc != 0

- name: Determine if firewalld installed
  command: "rpm -q firewalld"
  register: has_firewalld
  always_run: true
  ignore_errors: yes
  changed_when: false

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: has_iptables
  always_run: true
  ignore_errors: yes
  changed_when: false
