---
- name: Register for RHEL7
  redhat_subscription: state=present username="{{ lookup('file', '~/rhn_username') }}" password="{{ lookup('file', '~/rhn_password') }}" autosubscribe=true

- name: Enable RHEL7 Extra Repo
  command: "subscription-manager repos --enable rhel-7-server-extras-rpms"

- name: Enable the RHEL7 Kubernetes copr repo
  copy: src=eparis-kubernetes-epel-7.repo dest=/etc/yum.repos.d/eparis-kubernetes-epel-7.repo
  tags: eparis_repos

- name: Enable eparis extra repo
  copy: src=eparis-extras.repo dest=/etc/yum.repos.d/eparis-extras.repo
  tags: eparis_repos
